[package]
name = "sbv2-dict"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bincode = "1.3.3"
lindera-dictionary = "0.43.3"
serde = { version = "1.0.219", features = ["derive"] }
yada = "0.5.1"
